### PR TITLE
RFP: Reputation System

### PR DESCRIPTION
**Pull request by viaruc**

### CODE REVIEW

**Comment by viaruc** [comment]
Sorry couldn't add tags `proposal-type:rfp` and  `category:app-dev`

**Comment by eshon** [comment]
Hi @viaruc, 
Can you please email devgrants@filecoin.org so we can set up a chat to discuss this proposal? Also the next Wave 3 proposal deadline has been extended to April 15th.

**Comment by viaruc** [comment]
@eshon done that soon after submitting the proposal

**Comment by viaruc** [comment]
Hi @eshon I see that tags are still missing. Is all good with our proposal and can you confirm if you got an email from me at devgrants@filecoin.org?

**Comment by ErinOCon** [comment]
Archived

**Pull request closed without merging**
