### PR TITLE
RFP: Shared blocklists of CIDs; Open proposal: CID commenting

### PR DESCRIPTION
**Pull request by subsocialdev**
_Accidentally I put two proposals (PRF and Open) in this PR. I think it would be much convenient to split the proposals into two separate PRs. What do you think?_

## RFP: Shared blocklists of CIDs

A registry for sharing CID block lists on Substrate. It should be possible to provide an optional metadata around the reasons for blocklisting. A way for community members (regular users) to report CIDs to blocklist would also be useful.

Category tag: `category:app-dev`
Grant type tag: `proposal-type:rfp`

## Open proposal: CID commenting

A decentralized platform on top of Substrate and IPFS that allows community to share interesting/important CIDs and comment on them. Think of it as a decentralized Reddit or Hacker News for IPFS.

We are planning to built this project on top of Subsocial - a protocol for decentralized social networks on top of Substrate and IPFS. Please check out an [alpha version of Subsocial](http://dapp.subsocial.network/). And here is a presentation of Subsocial at Sub0 online conference organized by Parity Technologies: https://www.youtube.com/watch?v=NeDSaNxAjj4

Tag: `category:app-dev`.
Grant type tag: `proposal-type:open`

### CODE REVIEW

**Comment by siman** [comment]
BTW, we are the authors of the "Subsocial" project at IPFS: a Reddit-like dapp on IPFS, OrbitDB, with content encryption + pay-per-view on Ethereum.
https://hack.ethglobal.co/showcase/subsocial-recFoUlRK7vpScxh4

**Comment by subsocialdev** [comment]
Hi guys, we are back and ready to work on these two proposals.
Sorry for the delay in response, we have been quite busy with our Substrate grant for Web3 Foundation.

**Comment by subsocialdev** [comment]
The diagram for "Shared blocklists of CID"

Diagram: Shared Blocklists of Content CIDs

**Comment by subsocialdev** [comment]
The diagram for "CID commenting"

Diagram: CID Commenting

**Comment by subsocialdev** [comment]
Happy to start working on these two proposals as part of one project.
Let me know what you think :)

**Comment by ErinOCon** [comment]
Archived

**Comment by siman** [comment]
> Archived

why?

**Pull request closed without merging**
