### PR TITLE
RFP-DDPFT ehanced expected consensus

### PR DESCRIPTION
**Pull request by plotozhu**
DDPFT-- *Dynamic Delegated Power Fault Tolerance*,  is enhanced expect consensus algorithm to avoid VDF hardware

### CODE REVIEW

**Comment by pooja** [comment]
Thank you for submitting this proposal!

**Comment by plotozhu** [comment]
> Thank you for submitting this proposal!

Thanks, we've proved  liveness and fast finalization, and now working on a workable protocol source.

**Comment by pooja** [comment]
We've finished the wave 1 grant selection process. Can you please email devgrants@filecoin.org so we can share our decision and next steps, if any? In your email, please include a link to your proposal PR so we know who we're talking to!

Thanks,
Filecoin DevGrants team

**Comment by pooja** [comment]
Greetings,

Thank you for your application to the Filecoin DevGrants program. We appreciate your proposal!

You were not selected for a grant in Wave 1, but we hope that you consider applying again for a future DevGrant in a later wave.

We selected grants based on:
- what makes sense to build now based on where the Filecoin node implementations are
- the likelihood of your team being able to work independently of the Filecoin engineering teams working on the core client implementations
- degree of refactoring your proposal may require as the software clients evolve
- the integrity of the proposal and near-term value to the Filecoin ecosystem
- your commitment to the ecosystem and desire to maintain your project longer-term

As the Filecoin implementations advance towards Testnet and Mainnet, we hope you continue to consider new proposals for projects. We would love to see more applications from you in the future.

Please stay tuned for more Filecoin grant RFPs. :)

**Pull request closed without merging**
