### PR TITLE
Adding FVM RFP list with 1 new RFP idea

### PR DESCRIPTION
**Pull request by eshon**
Hi, this is 1 of 2 new RFPs for the FVM.

### CODE REVIEW

**Comment by mishmosh** [comment]
Overall looks great. I'm a little concerned about having only 1 technical sponsor (@raulk) due to turnaround times. Should we consider adding 1-2 more people?

@developerally suggested that we might include this as a project type in the general FVM tooling RFP (#592). It might be easier to share 1 link in the future rather than multiple to interested parties. Open to hearing thoughts either way.

**Comment by eshon** [comment]
It's not clear to me where we would share the specific RFP project description if we put this in the general FVM Tooling RFP. I would assume a project like FVM would require many RFPs to share project ideas.

If you mean using the previous dev grants wave 3-4-5 style of consolidating many RFPs into 1 big markdown file for FVM so people can browse all of them more easily, we can do that too. But FYI, we have another RFP project idea coming with multiple paragraphs.

**Comment by DeveloperAlly** [comment]
The idea of the general RFP was to be an umbrella RFP for any and all tooling and infrastructure proposals for FVM.
This means that any proposals for this RFP (and any other RFPs related to FVM tooling and infrastructure that you mentioned) would just submit to an overall category of RFP which is the umbrella FVM RFP (then there is no need to write separate RFPs for the many and diverse ideas and tools that we will need around this)

**Comment by DeveloperAlly** [comment]
Looking through the grants though - I can see where you are coming from too.
RE: 
> It's not clear to me where we would share the specific RFP project description if we put this in the general FVM Tooling RFP

I would suggest we add more details in the open FVM RFP to "Project Types" with this in it

**Comment by eshon** [comment]
Ok @DeveloperAlly please take a look:

- fvm-open-tools-infra.md contains a link to fvm-rfp-ideas.md
- fvm-rfp-ideas.md is set up to be expandable to more RFPs we add in the future

**Pull request merged**
