### PR TITLE
open-proposal-cambrian-protocol

### PR DESCRIPTION
**Pull request by NicWickman**
Proposal for development on a system for conditional resource allocation.

### CODE REVIEW

**Comment by realChainLife** [comment]
Hi @NicWickman Thank you for your proposal. The team will review this and get back to you!

**Comment by realChainLife** [comment]
@NicWickman Can you share how project this utilize Filecoin, IPFS, or related technologies?

**Comment by NicWickman** [comment]
@realChainLife It has been updated.

**Comment by realChainLife** [comment]
Hi @NicWickman thanks for the updates and technical details. We would like to fund the work outlined in the proposal. Please email devgrants@fil.org to discuss next steps.

**Comment by NicWickman** [comment]
@realChainLife done!

**Pull request merged**
