### PR TITLE
Open Grant Proposal: Filecoin Chinese community construction

### PR DESCRIPTION
**Pull request by yuwenhui**
Filecoin did not have a Chinese technology community from the DevNet, there are communication barriers for non-native English speakers. And Chinese miners and developers are more accustomed to WeChat communication.

We built Filecoin Chinese community for all the Chinese miners and developers. We created and maintaining Filecoin Chinese technology WeChat group with more than 1.4k users. There are tens of thousands of messages every day including hardware configuration, mining tutorial, troubleshooting, development sharing, bug trace and so on. We believe that these are the most active and useful technical community for Filecoin ecosystem.

We found that there are many duplicate questions after we created WeChat group, we also built an all in one [Filecoin Awesome resources Repo](https://github.com/CoinSummer/filecoin) for Chinese community. Including common resource links, commonly node operations, common Storage Miner operations, Seal Worker operations, environment variables, debugging, frequently asked questions, etc.

### CODE REVIEW

**Comment by jennijuju** [comment]
I can notice a huge positive impact from the effort CoinSummer's team has been putting into building the Chinese miner community. Their [Filecoin wiki](https://github.com/CoinSummer/filecoin) and wechat groups support have been very useful to the Chinese mining community, especially for someone new to the network.

For a community grant, i think it will be helpful if:
- one can help with building and maintainning a Chinese community forum with wikis on a GitHub repo that lives in [filecoin project](https://github.com/filecoin-project?q=&type=&language=)
- Recognize the star community members that contributes to the open sourced community and distribute the rewards

**Comment by philippbanhardt** [comment]
Hey @yuwenhui thank you for this proposal! Can you kindly email me at philipp@fil.org so we can discuss further?

**Comment by yuwenhui** [comment]
So far, the WeChat groups we created and maintained  has increased to 6, with 2.6k miners and developers totally. And [Filecoin Awesome resources Repo](https://github.com/filecoin-project/community-china) currently has 171 stars and 32 forks. The [Filecoin Community China Discussions](https://github.com/filecoin-project/community-china/discussions) also have 50 topics, more than 300 comments and reply.

**Comment by Fatman13** [comment]
Will there be any support for documentation/test/promotion of other implementation of filecoin for the Chinese audience too? More specifically Venus implementation. @yuwenhui

**Comment by yuwenhui** [comment]
@Fatman13 Sure, we are planing to support other implementation of filecoin.

**Pull request closed without merging**
