### PR TITLE
Open Proposal: Prometheus 

### PR DESCRIPTION
**Pull request by fireseeds**
Prometheus is a project focusing on creating a community-driven ecosystem website which starts with a few contributors to build up the first prototype that aims to be a community one-stop shop which would contain everything about the Filecoin community activities, including translation of filecoin-specs, beginner guides, ecosystem projects/team/tooling/grants display, workshops/tutorials, etc.

The content creation for the website will be governed by DAO to let the community manage it autonomously to further decentralized the project.

### CODE REVIEW

**Comment by fireseeds** [comment]
Hi, Filecoin team. Those should be: `category:docs`, `category:app-dev`, `category:community` and `proposal-type:open`

**Comment by eshon** [comment]
Hi @fireseeds,

Questions about your proposal:

1. How is the DAO funded? How are governance tokens distributed? Is it going to use Substrate-based tokens?

2. Your Resources for M1 - M3 don't list content contributors - is this content produced by the community or by your team?

**Comment by eshon** [comment]
Greetings,

Thank you for your application to the Filecoin DevGrants program. We appreciate your proposal.

Your team was not selected for this grant in Wave 2. (We have tried contacting your team about your proposal a few times but have not heard back.)

As the Filecoin implementations advance towards mainnet, we hope you continue to consider new proposals for projects. The idea of a Substrate DAO that relates to Filecoin was definitely interesting.

**Comment by fireseeds** [comment]
Hi, Filecoin-Project/Devgrants,

I've sent you the answer on 22nd Feb through email, it seems that you
didn't receive it?

Waiting for your reply.

Yours sincerely,
fireseeds team

**Comment by eshon** [comment]
We did not receive any email @fireseeds. The email is devgrants@filecoin.org.

**Pull request closed without merging**
