### PR TITLE
AIRport with Votecube seed project: Phase 1 - Basic Functionality Prototype

### PR DESCRIPTION
**Pull request by artem-v-shamsutdinov**

### CODE REVIEW

**Comment by realChainLife** [comment]
Thanks @artem-v-shamsutdinov for this propopal. Can you detail how the advertisement model will apply here. Also can you reduce the budget scope? You can do this by breaking down milestones in development phases that be funded phase-by-phase.

**Comment by artem-v-shamsutdinov** [comment]
> Thanks @artem-v-shamsutdinov for this propopal. Can you detail how the advertisement model will apply here. Also can you reduce the budget scope? You can do this by breaking down milestones in development phases that be funded phase-by-phase.

Just updated the reasoning behind a decentralized Advertisement Engine, added a new Economics + Monetization section and broke down the project into 7 Phases.

:)

**Comment by artem-v-shamsutdinov** [comment]
Specifically on the Distributed Advertisement Engine:
"The key risk is in figuring out how to monetize on the platform. To solve this we'll be building a decentralized Advertisement Engine. Being decentralized it will allow full decentralized applications to be built on top of AIRport. Without it Apps will have to rely on centralized advertisement platforms for their revenue. It also makes long term success of the project possible, providing revenue to the AIRport team for bug fixes and improvements."
A longer description is in the "Monetization" section.

**Comment by realChainLife** [comment]
Hi @artem-v-shamsutdinov thanks for all the refactoring you've done here. I'd like additional clarification on the scope of the proposal. Can you email devgrants@fil.org so we can schedule a call?

**Comment by artem-v-shamsutdinov** [comment]
Reduced proposal scope to one phase - which is a minimum demonstration of functionality.

**Comment by realChainLife** [comment]
Thanks for reworking the scope @artem-v-shamsutdinov could you also include a budget breakdown per milestone?

**Comment by artem-v-shamsutdinov** [comment]
@realChainLife - done.

**Pull request merged**
