### PR TITLE
Proposal for Open grants -  Trustable Deep Learning Project

### PR DESCRIPTION
**Pull request by Garima5**

### CODE REVIEW

**Comment by realChainLife** [comment]
Hi @Garima5 thank for this proposal, however its very abstract and the scope is very large. Can you refactor this to focus on components that will highlight Filecoin as a storage provider and bridge to other ecosystems.

**Comment by Garima5** [comment]
> Hi @Garima5 thank for this proposal, however its very abstract and the scope is very large. Can you refactor this to focus on components that will highlight Filecoin as a storage provider and bridge to other ecosystems.

Thank you for the feedback. I have refactored our proposal to highlight the deliverables and milestones that will utilize Filecoin as a storage provider and bridge to other ecosystems

**Comment by Garima5** [comment]
Hello Team,

Thank you for you feedback. I have refactored the proposal. I am also
sending it via email here. Kindly let me know if anything else is required
from our side.

Thank you
Kind regards
Garima

**Comment by realChainLife** [comment]
Hi @Garima5 I'd like to discuss various elements of your proposal, can you email devgrants@fil.org so we can schedule some time.

**Comment by Garima5** [comment]
Hello Team,

Thank you for reaching out. It would be great if we could schedule a
meeting this Tuesday (3 August) afternoon.

Thank you
Kind regards
Garima

**Comment by realChainLife** [comment]
Hi @Garima5 thank for you reworking the proposal, unfortunately, the development roadmap is still too abstract for a prototype. If you'd like to have a chat on how we can rework thid for possible resubmission at a later date, happy to do that please email me at sonia@fil.org

**Comment by Garima5** [comment]
Hello Ms. Sonia,


Thank you for your email. We are available for a discussion on Thursday
(evening is preferred). Please let us know your availability.


Thank you

Kind regards

Garima

**Comment by ErinOCon** [comment]
Archived

**Pull request closed without merging**
