### PR TITLE
RFP Submission : File ingestion + splitting

### PR DESCRIPTION
**Pull request by da-moon**

### CODE REVIEW

**Comment by eshon** [comment]
@damoonazarpazhooh:

When trying to build your library: 

`package github.com/damoonazarpazhooh/chunker/build: unknown import path "github.com/damoonazarpazhooh/chunker/build": cannot find package`

**Comment by damoonazarpazhooh** [comment]
@eshon give me a couple of days . I will setup a dockerized build pipeline.

**Comment by pooja** [comment]
Hi @damoonazarpazhooh do you have any docs for our team to try out?

**Comment by damoonazarpazhooh** [comment]
@pooja I will write the docs and set up a dockerized build pipeline this weekend. I have been quite busy the past week so I couldn't do it any sooner. sorry about that.

**Comment by pooja** [comment]
We've finished the wave 1 grant selection process. Can you please email devgrants@filecoin.org so we can share our decision and next steps, if any? In your email, please include a link to your proposal PR so we know who we're talking to!

Thanks,
Filecoin DevGrants team

**Comment by pooja** [comment]
Greetings,

Thank you for your application to the Filecoin DevGrants program. We appreciate your proposal!

You were not selected for a grant in Wave 1, but we hope that you consider applying again for a future DevGrant in a later wave.

We selected grants based on:
- what makes sense to build now based on where the Filecoin node implementations are
- the likelihood of your team being able to work independently of the Filecoin engineering teams working on the core client implementations
- degree of refactoring your proposal may require as the software clients evolve
- the integrity of the proposal and near-term value to the Filecoin ecosystem
- your commitment to the ecosystem and desire to maintain your project longer-term

As the Filecoin implementations advance towards Testnet and Mainnet, we hope you continue to consider new proposals for projects. We would love to see more applications from you in the future.

Please stay tuned for more Filecoin grant RFPs. :)

**Comment by eshon** [comment]
@da-moon: I was trying it quickly on a Mac but can try it out on an Ubuntu or ArchLinux. (Also I'm not a GoLang Dev but a UX person). 

I think what would be more helpful though is just a README of what your tool is doing and your roadmap for a grant. This RFP may stay open for Wave 2, let me double check and get back to you.

**Comment by da-moon** [comment]
@eshon I made the repo private since I wasn't selected. If you are still interested, I can make it public again and write the makefile in a way that you can try different CLI commands within a docker container.
By the way, thank you for pointing out those issues, I would have totally missed them if you didn't point them out.

**Comment by eshon** [comment]
hey @da-moon I will close this PR for now. You are welcome to reapply in Wave 2 for the same RFP.

**Pull request closed without merging**
