### PR TITLE
Open proposal: C2D-aka-HTTP2IPFS | Application for Filecoin Open Grant

### PR DESCRIPTION
**Pull request by voidao**
Please tag/label this as `category:devtools-libraries` and `proposal-type:open`. Thanks!

### CODE REVIEW

**Comment by voidao** [comment]
@pooja Please tag/label this as category:devtools-libraries and proposal-type:open. Thanks!  :)

**Comment by voidao** [comment]
@eshon Thank you!  👍

**Comment by eshon** [comment]
Hi @voidao,

Its not clear from this proposal what you would be building. You can also email devgrants@filecoin.org if that's easier.

Also does your team have any example live projects or Github repos that you want to point out?

**Comment by voidao** [comment]
Hi @eshon,

Please kindly refer to our Github org [C2D-aka-HTTP2IPFS](https://github.com/C2D-aka-HTTP2IPFS). We had just get started, but I think that you could get some sense on what we would be building from the [roadmap](https://github.com/C2D-aka-HTTP2IPFS/c2d-roadmap) repo and others. Besides, I would probably email [devgrants@filecoin.org](devgrants@filecoin.org) with more comprehensive information.

Thanks!

**Comment by voidao** [comment]
It’s overall result would be sth like the current [Internet Archive](https://www.archive.org/), but with the contents transported to IPFS/FileCoin DSN and distributed/cached into personal devices, which eventually would never be broken in practice.  @eshon

**Comment by voidao** [comment]
Adding some cases with pictures:

- ipfs.io official resources are blocked(DNS hijacking), but accessible via distribution as shown below:
IPFS Resources Case

- Internet Archive is currently not accessible as well
Internet Archive Case

**Comment by eshon** [comment]
@voidao - Can you clearly define the devtool or library in software you would be building? Your resources are not examples of software.

**Comment by voidao** [comment]
@eshon - Does something like the [c2d-video-ibipfs.js](https://github.com/C2D-aka-HTTP2IPFS/c2d-video-ibipfs.js), which basically would be a HTTP2IPFS transporter implemented in Javascript, match what you are asking?

> @voidao - Can you clearly define the devtool or library in software you would be building? Your resources are not examples of software.

**Comment by voidao** [comment]
@eshon - Adding [iDrop](https://github.com/ibipfs/idrop) as one more scenario.

**Comment by eshon** [comment]
Greetings,

Thank you for your application to the Filecoin DevGrants program. We appreciate your proposal.

Your team was not selected for this grant in Wave 2.

We appreciate your excitement for the IPFS and Filecoin ecosystem, but hope to see more concrete and specific technical proposals for software and tools that your team can build.

If your team is less technical, consider applying for a community dev grant or we're also looking for cultural institutions and collaborators that may want to store their digital archives on Filecoin, if you know of any in Asia.

Please stay tuned for more Filecoin grant RFPs. :)

**Comment by voidao** [comment]
Thank you @eshon :)

**Pull request closed without merging**
