### PR TITLE
Open Grant Proposal: Adapt IPFS to ML and Data Pipelines 

### PR DESCRIPTION
**Pull request by aronchick**

### CODE REVIEW

**Comment by mishmosh** [comment]
@aronchick Thanks for your proposal! Especially nice to see Milestone 4 (documentation and demos) included. We'll be reviewing this tomorrow.

Quick clarification: are you submitting _on behalf of_ Luke Marsden who would be the grant recipient and implementer?

**Comment by lukemarsden** [comment]
Hi folks, yes, David is submitting on my behalf. Hi btw 👋 😄

**Comment by aronchick** [comment]
@mishmosh i'll be contributing (some) but Luke will be doing a lot of the coordination and implementation. We will only be successful, however, if we build an actual community that goes beyond him. 

I'm submitting because _i_ want this for IPFS though :)

**Comment by nollied** [comment]
@aronchick do you have discord? i'd like to communicate here as I'm doing the same thing with [hub](https://github.com/activeloopai/Hub), I think it will save a LOT of development time!

**Pull request merged**
