### PR TITLE
Open Proposal: Cadbury Storage

### PR DESCRIPTION
**Pull request by susmit**
**Project-title:**  Cadbury Storage
**Category tag:** category:app-dev
**Grant type tag:** proposal-type:open

### CODE REVIEW

**Comment by prastut** [comment]
Hi @susmit, really cool idea. Was curious about how are you approaching the content ownership problem on Filecoin and IPFS? 

You mention that "Data generated from the meetings have a strong use-case to be stored (especially for universities, ed-tech startups and big corporations)" - which I agree with but I see that these people won't want their data to be available for everyone to read. 

As far as I know, it's still an open problem. See: https://github.com/protocol/ResNetLab/blob/master/OPEN_PROBLEMS/PRESERVE_USER_PRIVACY.md

**Comment by susmit** [comment]
Thanks ! @prastut  User coming to Cadbury meet can store the data they generate ie their audio ,video feed. Since to interact to Filecoin via textile powergate we store tokens in user 3box profile private field . 

As of now their are research online and lots of idea we are experimenting with for the same ,  obsfucation, Stark zkp, Access control by encryption etc.

**Comment by philippbanhardt** [comment]
Hey @susmit - thanks for this PR. What is a good email to reach you at?

**Comment by susmit** [comment]
@philippbanhardt susmit9370@gmail.com

**Comment by philippbanhardt** [comment]
Just noting here that we were not able to fund as part of wave 5

**Pull request closed without merging**
