### PR TITLE
Open Proposal: BitBlock

### PR DESCRIPTION
**Pull request by PatrickNercessian**

### CODE REVIEW

**Comment by realChainLife** [comment]
Hi @PatrickNercessian Thank you for your proposal. How will the team identity and engage the target audience. Can you add  details to the proposal?

**Comment by PatrickNercessian** [comment]
> Hi @PatrickNercessian Thank you for your proposal. How will the team identify and engage the target audience. Can you add details to the proposal?

Hello @realChainLife. Of course, thank you for your consideration. I assume you mean how will I attract users, please correct me if I misunderstood. 

I was planning to reach out to current popular content creators on TikTok and YouTube and give a pitch on how they could dramatically increase their income by posting on BitBlock. I would start with cryptocurrency content creators, as they would be most likely to understand and adopt BitBlock's economics and technology, and expand to other content creators over time. The idea is that bringing creators to the app will initially bring their biggest fans to the app first, and then word of mouth will continue to grow the user-base.

After the hypothetical initial sale(s) of the related token, the DAO would automatically start depositing tokens into creators' wallets (perhaps before advertisers are even onboarded, as the DAO would have its own initial treasury) based on viewership. Either directly before or after this, advertisers would be onboarded and able to pay the DAO to promote their content. Next, the DAO would pay viewers for each advertisement they view. As each component of the economic cycle is completed, the incentives for users to join the platform will continue to grow.

We could even explore using the DAO's treasury to buy advertisements or to pay content creators (who are already on BitBlock) to post about the application on their other platforms.

**Comment by realChainLife** [comment]
Thanks for the additional details @PatrickNercessian a leading question here is how building an advertising model on the platform intersects with the user data cadence on decentralized system. What benchmarks will you be using for the advertising algorithm?

**Comment by PatrickNercessian** [comment]
> Thanks for the additional details @PatrickNercessian a leading question here is how building an advertising model on the platform intersects with the user data cadence on decentralized system. What benchmarks will you be using for the advertising algorithm?

Hi @realChainLife. Thank you for the great question, I updated the grant proposal with an answer and copied it below for ease-of-access:

The _y_-th video shown to a viewer will be randomly selected from a global database of “promoted” videos, rather than the global database of “user” videos. _y_ will be a random integer between, say, 5 and 15. This will keep advertisements from monotonously becoming a story of “every _y_ videos I’ll see an ad”. The _y_ range can actually be set individually by each viewer, so they could choose to not see any advertisements at all (and thus forego any income).

Advertisers will be able to upload and promote content through the application. In fact, users themselves will be able to promote their own content through the application, blurring the line between advertisers and users (although a “[Sponsored]” flag will always be displayed when a viewer is shown promoted content). After uploading a normal video, advertisers/users will be able to sign a smart contract promoting their video a certain number of times. This will cost a certain amount “per-view”.

For example, let’s say Company X wants to show their advertisement to 1000 people, and it costs 0.01 tokens per view. After uploading their video, they will sign a smart contract transaction which sends 10 BitBlock tokens (name TBD) to the BitBlock DAO along with “CID: xyz” and “numPromotedViews: 1000”. Every time a viewer is shown the promoted video, they sign a smart contract which decrements the numPromotedViews on that video and awards them some BitBlock tokens for watching an advertisement. When numPromotedViews reaches 0, the advertisement is no longer displayed to viewers.

This is a clear target for malicious actors and botnets, which is why using smart contracts seems to be the best option rather than allowing users access to the global database. Additional security decisions may be necessary such as daily limits on ads watched per user and/or a minimum required balance for a user to be able to participate in these smart contracts. Furthermore, the economics of viewers receiving payments from DAOs and sending payments for gas fees must be automatically balanced to ensure that viewers are always net positive for having watched an advertisement.

As a reminder, the above outlined technical plan for advertising may not come to fruition. It is certainly possible that unforeseen technical or economic difficulties arise that make this system infeasible or impossible. For example, if no smart contract platform has fees that are inexpensive enough to result in viewers and creators being net positive for every interaction. As a result of this uncertainty, I have requested $0 for this milestone and assigned a timeframe of “Unknown”. Even without this economy, BitBlock would still be a competitive application for the likes of TikTok, YouTube, etc. and would provide huge value to the Filecoin ecosystem by having users indirectly use Filecoin to store their content.

If you have any concerns or questions, or disagree and think the advertisement system is an absolute necessity, please contact me and we can discuss this further. Thank you for your continued consideration!

**Pull request merged**
