### PR TITLE
Open Grant Proposal - Discovery

### PR DESCRIPTION
**Pull request by Cali93**

### CODE REVIEW

**Comment by realChainLife** [comment]
hi @Cali93 thanks for this proposal. How will you identify and engage potential learners in the community? Please add any additional details on this to the proposal.

**Comment by Cali93** [comment]
Hi @realChainLife, thanks for this good question.
The question and the answer have been added on this commit:
https://github.com/filecoin-project/devgrants/pull/318/commits/251bb351604daa2a8a377d6cf9e9a13280dcae2a

**Comment by realChainLife** [comment]
Thanks for the additional details @Cali93. We would like to fund the work outlined in the proposal. Please email devgrants@fil.org to discuss next steps.

**Comment by Cali93** [comment]
### Milestone 1 & 2 retrospective

**Milestone 1**  - 4 weeks (10/25/2021 - 11/22/2021)
User Interface with following functionality:
- [x] Enable user to create new project, by ~~uploading to gitbook ~~ completing a form on the dApp.
- [x] Build (github action)[https://github.com/Discovery-Labs/dCompass-Gitbook-action] for uploading files to Filecoin and IPFS. 
- [x] Enable image upload using web3.storage and web3.js https://github.com/Discovery-Labs/dCompass/blob/8a1ae49c260f5597a97ffc6b2a54985fbc27f5ab/packages/dapp/src/pages/api/image-storage.ts#L46

**Milestone 2: 3 months** (11/23/2021 - 02/21/2022)
Implement & extend the multiple smart contracts that:
- [x]  Will control the access, approvers, and minting of NFTs https://github.com/Discovery-Labs/dCompass/blob/8a1ae49c260f5597a97ffc6b2a54985fbc27f5ab/packages/hardhat/contracts/ProjectNFT.sol#L78
- [x] Will keep track of pending eligible addresses for future minting https://github.com/Discovery-Labs/dCompass/blob/8a1ae49c260f5597a97ffc6b2a54985fbc27f5ab/packages/hardhat/contracts/ProjectNFT.sol#L133
- [x] Will use Identity-Link Services to link Github account to Ethereum addresses https://github.com/Discovery-Labs/dCompass/blob/staging/packages/dapp/src/components/custom/profile/AddGithubAccountScreen.tsx
- [] Will build a chainlink external adapter (deproritized to focus on the quest completion and reward claims)

**Pull request closed without merging**
