### PR TITLE
RFP FILExplorer AHC Team

### PR DESCRIPTION
**Pull request by lrgeoemtry**
The Anthem Holdings Company Proposal for the FIL Explorer 
*Subject to change, expand, evolve*

### CODE REVIEW

**Comment by lrgeoemtry** [comment]
@pooja let me know what you think

**Comment by pooja** [comment]
This is great @lrgeoemtry! RFP deadline is Sept 30, so can't guarantee we're going to get to it before then. But there's always a chance we will!

**Comment by lrgeoemtry** [comment]
Hey no problem just pinging your radar! @juliepeace

**Comment by lrgeoemtry** [comment]
closing this to update. im sure this will happen a few more times. @pooja

**Pull request closed without merging**
