### PR TITLE
Metatron Proposal

### PR DESCRIPTION
**Pull request by Flaxscrip**
Hello Filecoin team - 

Please take a look at a project that I hope will attract your interest. 

I was referred to you by Brett B. who thought your program could help launch Metatron. I am thankful to him for pointing me in your direction. The IPFS/Filecoin ecosystem seems like a natural home for Metatron. 

I would love an opportunity to connect with you live.

Thank you for the great work you do for data decentralization.

Peace!

Christian.

### CODE REVIEW

**Comment by realChainLife** [comment]
Hi @Flaxscrip Thank you for your proposal. The team will review this and get back to you!

**Comment by realChainLife** [comment]
@Flaxscrip We would like to fund the work outlined in your proposal, kindly email devgrants@fil.org to discuss the next steps.

**Comment by Flaxscrip** [comment]
Hello - Thank you for your response. My apologies for the delayed response. I only looked at the notifications now. I will reach out by email. Thank you.

C.

**Comment by ErinOCon** [comment]
Hi @Flaxscrip, I noticed you inquired about the Metatron project [here](https://github.com/filecoin-project/devgrants/issues/1000). If you have a new update available regarding the status of this project, please reach out to grants@filecoin.org. 

We would be happy to hear from you!

**Comment by Flaxscrip** [comment]
@ErinOCon - We are no longer pursuing the Metatron Launch project. 

The team is highly appreciative of the financial assistance provided by the Filecoin Foundation. The code remains available as OSS on Github and indeed, we plan on using the existing Metatron technology in future projects. The financing from Filecoin Foundation was meant to support us through a pilot program with the Ethical Data Alliance that has since been closed. 

We continue to be strong promoters of IPFS technology. We hope to be able to present new proposals to the Foundation in the not too distant future. 

The remaining funds originally assigned to the Metatron

**Comment by ErinOCon** [comment]
Hi @Flaxscrip, thank you for the update. It looks like your last sentence cut off. Did you have a new intended purpose for the remaining funds?

**Comment by Flaxscrip** [comment]
My solo goes for that.  No future use of remaining funds.  Thank you again for the support.  We hope to bring new projects to the Foundation in the future.

**Pull request merged**
