### PR TITLE
 Open Grant Proposal: Lotus Farcaster V2

### PR DESCRIPTION
**Pull request by s0nik42**
Hi @eshon, please find in attachment the Proposal for lotus farcaster V2

### CODE REVIEW

**Comment by jamerduhgamer** [comment]
Looking forward to these updates! Lotus Farcaster has been extremely helpful in keeping track of a ton of info on a nice GUI interface.

**Comment by kirtapenator** [comment]
The farcaster has been amazing in helping visualize the miner and worker statuses all in one place! Can't wait for the new deal section and sector state functionality to arrive! Keep up the great work @s0nik42 !

**Comment by benjaminh83** [comment]
This will be very helpful for all small-medium miners! I would love to se this next level for farcaster.

**Comment by PatrickDeuse** [comment]
we are using the farcaster as a base for a lot of our dashboards - waiting for the new version to contribute some of them after adjusting to the new version!

**Comment by shawnp0wers** [comment]
I use farcaster at multiple locations, it's an incredible resource, especially for small to medium miners who are trying to eek out every bit of performance. The addition of more deal information would be invaluable.

**Comment by gradoj** [comment]
Really nice to have a gui visualization/monitoring tool. Very useful for multiple systems running in a complex distributed pipeline. Would love to see this development continue.

**Pull request closed without merging**
