### PR TITLE
 Archive Website to Filecoin & Filecoin Explorer for Wave 5

### PR DESCRIPTION
**Pull request by DecentralTech**
## Project Description

A browser extension that allows users to archive websites to IPFS and backup to Filecoin. This extension could also provide a Filecoin wallet so that users can pay for archival and as a way to keep track of what they have saved.
In the future this could be expanded to ways to collaborate on and share archived bookmarks in online communities or as bookmarking services (e.g.  _Pinboard_ , Pinterest, etc.)
A Twitter bot such as the former  _Link Archiver_  could automatically archive websites from tweeted links.
This project would need to explore the required infrastructure for these services.

### CODE REVIEW

**Comment by DecentralTech** [comment]
Please read Code :
https://github.com/DecentralTech/IPFSFilecoinArchiveExtension

**Comment by DecentralTech** [comment]
Filecoin Explorer:

image

**Comment by DecentralTech** [comment]
image

**Comment by philippbanhardt** [comment]
Thanks for submitting your proposal @DecentralTech - we are excited to dig in and will revert with feedback / questions within the next few days.

**Comment by philippbanhardt** [comment]
Just noting here that we were not able to fund as part of wave 5. @DecentralTech are you still interested in pursuing this project, funded with a dev grant?

**Comment by ErinOCon** [comment]
Archived

**Pull request closed without merging**
