### PR TITLE
New Dev Grants Proposal - Blockchain Solution for AI using Filecoin

### PR DESCRIPTION
**Pull request by WillTechMusing**

### CODE REVIEW

**Comment by realChainLife** [comment]
Thanks for the proposal @WillTechMusing we'll review this and get back to you!

**Comment by WillTechMusing** [comment]
@realChainLife thank you for your review and feedback. I have updated the proposal to answer your questions.

- How will storing the algorithm on ipfs contribute to better ML algorithms? Can you detail the value prop?

It will make ML scientists a lot more productive to get to both data and ML algorithms at the same time, rather than just dataset itself. This will greatly simplify other users and application data scientists to rapidly use them as references to develop further or improved ML models.

- Is the main deliverable building a layer to make uploading data to Filecoin easier?

yes it will not only have upload, but also search, view and download.

**Comment by realChainLife** [comment]
Thanks for sharing this details @WillTechMusing a final question here: have you identified who will likely use this tool, and how you'll introduce it to them?

**Comment by WillTechMusing** [comment]
Great question. Thanks for asking.

The target audience fo the tool and datasets are those who wants to use these open datasets for research and machine learning predictions, likely majority of the AI/ML data scientists and practitioners in the world. The initial thoughts on how to get to them:

- Publish an article about how to use the tool, and the benefits of it with FileCoin as storage for datasets and algorithms into multiple blogs and social media (https://towardsdatascience.com/, https://medium.com/topic/data-science)
- Share the tool under https://rivering.ai web site (being constructed)
- Host a small competitions to attract Data Science to use the tool in https://www.kaggle.com/competitions
- Share the tool in Filecoin community (I am an active member of it) and ask for suggestions to share and promote this tool

We will develop additional outreach and collaboration when comes to the marketing phase (part of the work in later of this project).

Hope these helps @realChainLife. Please let me know if you have any additional questions.

**Comment by realChainLife** [comment]
Thanks @WillTechMusing we'd like to fund the work in the proposal. Please email devgrants@fil.org to discuss next steps!

**Pull request merged**
