### PR TITLE
open-proposal

### PR DESCRIPTION
**Pull request by AmySeidman**
Hey Eva. this is my proposal for FileCoin. I hope I made it in time :)

### CODE REVIEW

**Comment by AmySeidman** [comment]
This should have the following tags:
Project Category: category:app-dev
Grant category: proposal-type:open

Still looking at Youtube to see how to tag it...as  tag settings are missing from my github interface.

**Comment by AmySeidman** [comment]
> Hey Eva. this is my proposal for FileCoin. I hope I made it in time :)

Greetings Eva, are you still on this side of the project? I have been trying to update this grant proposal. Also had a conversation with Sven. I would love to check in on this and update you on where we are now. 

:)

**Comment by AmySeidman** [comment]
@ErinOCon @eshon Checking to see if you are seeing this request to merge and complete this :)

**Comment by AmySeidman** [comment]
@ErinOCon  @eshon  hoping you see my request to merge changes. :)

The current version is here: 
 https://github.com/AmySeidman/devgrants/blob/patch-1/open-grant-proposals/open-proposal-BFLO_AND_THE_SDGs.md

Original: 
https://github.com/filecoin-project/devgrants/pull/195

**Comment by ErinOCon** [comment]
Archived

**Pull request closed without merging**
