### PR TITLE
Open Proposal: Filecoin Flutter

### PR DESCRIPTION
**Pull request by molekilla**
@luissanchez0305

### CODE REVIEW

**Comment by philippbanhardt** [comment]
Hey @molekilla - thank you for this proposal and apologies for the (epic) late response; I am afraid this fell through the cracks. Are you still interested in pursuing the project? If yes, then would be great to chat!

**Comment by molekilla** [comment]
> Hey @molekilla - thank you for this proposal and apologies for the (epic) late response; I am afraid this fell through the cracks. Are you still interested in pursuing the project? If yes, then would be great to chat!

Oh yeah, I never received any input, yes let's do it!!!

**Comment by molekilla** [comment]
@philippbanhardt Once we chat, let's review the original plan, some of these tech we already developed (eg IPLD, blockchain) and need to reorg the project plan and change team members

**Comment by ErinOCon** [comment]
Archived

**Pull request closed without merging**
