### PR TITLE
PR for RFPs:Monitoring Tool for Miners

### PR DESCRIPTION
**Pull request by s0nik42**
hi @eshon @hsanjuan, in attachement the PR for lotus-farcaster a Visualization and Analytics tool for Lotus Filecoin node It leverages Prometheus, Grafana and Python.

Please don't hesitate to reach out to me if you've got any question. (slack : @s0nik42)

Julien

### CODE REVIEW

**Comment by s0nik42** [comment]
Hi  @eshon @hsanjuan, could you provide insight on this and the next steps ?

Thank you,

Julien

**Comment by hsanjuan** [comment]
Sorry, I will defer to @eshon, I am not really involved in devgrant work.

**Comment by s0nik42** [comment]
Ok, thank you Hector :) anyway if you want to test the dashboard you are more than welcome

**Comment by eshon** [comment]
HI @s0nik42 I'll review this with Ribasushi early next week and respond soon

**Comment by s0nik42** [comment]
Excellent ! thank you very much !

**Comment by s0nik42** [comment]
Hi @eshon, hope you are fine, any news on this ?

**Comment by flyworker** [comment]
I have tested the v0.0.1 @s0nik42 give me, it works great.

**Comment by eshon** [comment]
Hi @s0nik42, thanks for the proposal. Can you please email devgrants@filecoin.org so we can set up a brief chat to review the dashboard?

**Comment by s0nik42** [comment]
Hi eshon, I emailed the adress, did you receive it ?

**Review by s0nik42 — COMMENTED** [review]
Add Video tutorial and Docstring

**Comment by ErinOCon** [comment]
Archived

**Pull request closed without merging**
