### PR TITLE
ipfs sre community proposal

### PR DESCRIPTION
**Pull request by taoshengshi**
refer the detail in attachments.

### CODE REVIEW

**Comment by Naturefir** [comment]
### 协议学院 **二月 · 绀香**春节21天公益直播活动
image
二月 · 绀香公益直播活动复盘资料：https://www.kdocs.cn/l/ckDGEYEhxb5V

### 协议学院 **三月 · 桃良**公益直播
三月 · 桃良公益直播活动数据
image

image

四月 · 秀蔓线上线下活动主题活动正在进行中
image

**Comment by Naturefir** [comment]
### 协议学院 **二月 · 绀香**春节21天公益直播活动
二月 · 绀香公益直播活动复盘资料：https://www.kdocs.cn/l/ckDGEYEhxb5V
image

**Comment by Naturefir** [comment]
### 协议学院 **三月 · 桃良**公益直播
三月 · 桃良公益直播活动数据
image
image

**Comment by Naturefir** [comment]
### 协议学院 **四月 · 秀蔓**线上线下活动主题活动正在进行中
image

**Comment by Naturefir** [comment]
### 协议学院 **四月 · 秀蔓**线上线下活动主题活动正在进行中
image

**Comment by realChainLife** [comment]
Hi @Naturefir thanks for the rephrase, please email sonia@fil.org and philipp@fil.org so we can continue to detail your proposal.

**Comment by Naturefir** [comment]
Hey! Sonia,Philipp,

I am Ruian Bao, former Community engineer from IPFS-Force.

I would like to share some personal news firstly. After nearly 2 years, I’m
leaving IPFS-Force this month, to a new role, new startup dedicated on
Filecoin & IPFS SRE community. It’s been a wonderful, wild, expansive,
amazing ride for the past years. I’m somehow lucky enough to have built a
career around the Filecoin mining. May be IPFS-Force is some kind of giant
in this area, I am so glad with my past work.

With the volunteers from the community, I have hosted the 21 days Filecoin
mining podcast event during the Spring Festival. After that ,we continue
deliver podcast in the March, April, May. Along with the Covid-19  begins
to brighten in China, We hosted weekly and monthly offline meetups. Because
of the public interest nature, we put much effort and money to these
activities from ourselves.

With the consideration of much pain points in Filecoin&IPFS SRE area as I
mentioned in the devgrant application, and We believe we could make it
better, Now, I want to dedicated myself to Filecoin&IPFS SRE community.

From the traditional SRE (http://www.greatops.net/) to Blockchain SRE,there
is a long way todo. But We dare to do. That's the IPFS SRE's mission and We
need your help and support.

Our detail plan with some "todo" and "on-going",please refer the attachment
in IPFS SRE Community
<https://github.com/filecoin-project/devgrants/pull/238>

Could you please help us to refine our idea? please let me know.


Thanks!
Ruian

Sonia John ***@***.***> 于2021年5月18日周二 上午4:24写道：

**Pull request closed without merging**
