### PR TITLE
Img8 open proposal.

### PR DESCRIPTION
**Pull request by 0xroad**
We are building an image processing and optimization protocol built on top of IPFS/Filecoin for web3 developers, designers, and creators. The protocol empowers the target users to easily rendering optimized and resized images to fit any design in real-time responsively by CIDs.

A feedback I've got from the [IPFS community Discord](https://discord.com/channels/806902334369824788/847893063841349652/890263848072908860)

### CODE REVIEW

**Comment by realChainLife** [comment]
Hi @0xatm thank you for your proposal. Could you provide additional technical details of the gateway architecture. Please add these in the development roadmap of the proposal.

**Comment by 0xatm** [comment]
> Hi @0xatm thank you for your proposal. Could you provide additional technical details of the gateway architecture. Please add these in the development roadmap of the proposal.

Hi @realChainLife , I've updated it in the commit 6f3aa15435cc2884391313bbefcbba4059e29da8, please have another review. Thanks

**Comment by realChainLife** [comment]
hi @0xatm thanks for updating the proposal. Are you also able to rework it specifically for prototype development and within a budget cap of up to $50k

**Comment by 0xatm** [comment]
> hi @0xatm thanks for updating the proposal. Are you also able to rework it specifically for prototype development and within a budget cap of up to $50k

Hi @realChainLife , yes, sure, that sounds reasonable to build a running prototype first and then see what can be done next. I'll revise a bit of the development roadmap to narrow down the scope and within your suggested budget.

**Comment by 0xatm** [comment]
> hi @0xatm thanks for updating the proposal. Are you also able to rework it specifically for prototype development and within a budget cap of up to $50k

Hi @realChainLife , thanks for your patience. I've updated the development scope and budget accordingly in the commit 53fee47485e7311b2d7cfdde5707743c9a1972c1, please have another review.

**Pull request merged**
