### PR TITLE
Open Proposal: Add Filecoin support to ENS

### PR DESCRIPTION
**Pull request by brantlymillegan**

### CODE REVIEW

**Comment by parkan** [comment]
hey @brantlymillegan! I think part (1) of the proposal is solid and straightforward -- associating accounts with ENS names is a no-brainer, the only question is whether they would be associated with a new ENS TLD (.fil or similar) or attached to an existing .eth (or w/e) TLD name

part (2) (naming and locating content) is a bit trickier and probably requires clarifying the retrieval story first -- there is not presently a standard mechanism for locating an arbitrary piece of content by CID in the filecoin network (@eshon please correct me if I'm wrong), and from a user perspective the retrieval could look very different depending on how the item is stored

in a sense, the existing IPFS records could map to the equivalent item stored in filecoin, unless you specifically want to name filecoin pieces, or specific CommR IDs (particular to a miner)

my suggestion would be to split up the part (1) of this proposal as a separate quick turnaround project and consider exactly what naming things on filecoin looks like in more detail for a separate part (2) proposal

**Comment by eshon** [comment]
Filecoin (data) CIDs and IPFS CIDs are the same. So aside from adding Filecoin addresses, more help with how to build a resolver + tutorial would be useful, or you can reduce the scope @brantlymillegan and we can find someone else to help with a resolver.

There is also a way to run an IPFS node in tandem with a Filecoin node and pull data from each other.

For (1) This repo helps explain the [Filecoin address reference in the Spec](https://filecoin-project.github.io/specs/#appendix__address)
https://github.com/NodeFactoryIo/filecoin-address

**Comment by brantlymillegan** [comment]
> the only question is whether they would be associated with a new ENS TLD (.fil or similar) or attached to an existing .eth (or w/e) TLD name

You'd be able to add it to any ENS name, as it already the case for lots of cryptocurrencies (see [the records for brantly.xyz](https://app.ens.domains/name/brantly.xyz) as an example). We won't be making any new TLDs, but we have .ETH, some DNS ones, and soon all of DNS.

> Filecoin (data) CIDs and IPFS CIDs are the same.

Will the prefix ("ipfs://") be the same, or is there a new one? Just wondering if we need to change anything about how our Content record works to support Filecoin CIDs.

Also, I included in my proposal: "We can add ENS functionality to a Filecoin client of your choosing." I'm thinking if you have a Filecoin wallet or some client in which users will be pasting in FIL addresses to send Filecoin, we could add ENS support. Any interest here?

**Comment by eshon** [comment]
> Will the prefix ("ipfs://") be the same, or is there a new one?

I think users can default to the existing IPFS resolver - or convince us otherwise. A "fil://Qme…" resolver doesn't seem necessary and you could just have a IPFS resolver be Filecoin-enabled to kick off the potential pay-to-retrieve workflow if it learns that the content CID is not in IPFS but is in Filecoin.

If you support both "ipfs://Qme.." and "fil://Qme…" then you'd have an IPFS resolver that also checks Filecoin, or a Filecoin resolver that also checks IPFS, but other than going straight to Filecoin and kicking off pay-to-retrieve right away this doesn't seem minimal for ENS or users.

> Filecoin wallet or some client

1. Can the resolver be a JS library that storage client dapps can include? 
2. There's a Metamask SNAP plugin in the works
3. This might be nice as a web app page as an tutorial to other storage clients

In [eip-1577](https://eips.ethereum.org/EIPS/eip-1577) are both CIDv0 and CIDv1 already supported?

**Comment by parkan** [comment]
@eshon modern CIDs are fully supported in ENS, superseding that EIP

**Comment by eshon** [comment]
There's also a Filecoin integration with Trustwallet

**Comment by brantlymillegan** [comment]
@parkan I have updated the PR with the reduced scope we discussed on our call today.

**Comment by eshon** [comment]
@brantlymillegan - Can you please email devgrants@filecoin.org so we have your email? Got a returned DNS error from the brantly.xyz address

**Comment by brantlymillegan** [comment]
> @brantlymillegan - Can you please email [devgrants@filecoin.org](mailto:devgrants@filecoin.org) so we have your email? Got a returned DNS error from the brantly.xyz address

Huh that's weird. My work email is brantly@ens.domains. I'll also email the dev grants email address.

**Pull request closed without merging**
