### PR TITLE
Open Proposal: Meme of the Day

### PR DESCRIPTION
**Pull request by BTCAlchemist**
category:app-dev
proposal-type:open

### CODE REVIEW

**Comment by philippbanhardt** [comment]
Thanks for submitting your proposal @BTCAlchemist - we are excited to dig in and will revert with feedback and potential questions within the next few days.

**Comment by philippbanhardt** [comment]
@BTCAlchemist what is a good email / your slack to reach you at?

**Comment by BTCAlchemist** [comment]
Hi @philippbanhardt, you could reach me at matthew@planningcrypto.com or on Filecoin Slack (member ID U019WA9L0M9). I look forward to hearing from you.

**Comment by philippbanhardt** [comment]
Just noting here that we were not able to fund this proposal in wave 5.

**Pull request closed without merging**
