### PR TITLE
Open-proposal-Gateway . submitted by bloXroute & IPFS-Force

### PR DESCRIPTION
**Pull request by steven004**

### CODE REVIEW

**Comment by eshon** [comment]
Hi @bloXroute and @IPFS-Force,

Questions about your proposal:

1. Can any of this functionality be open sourced as independent libraries/modules that are not specific to bloXroute's protocol that others can re-use? If so, what components?

2. Will everything be in python or what other languages will you use?

3. Will users of the BDN require BLXR tokens on Ethereum?

4. The proposal doesn't mention hosting the distributed cloud infra for the BDN - how is that funded?

**Comment by steven004** [comment]
+ Shen from bloXroute.

**Comment by eyalmarkovich** [comment]
Hi @eshon 

> 1. Can any of this functionality be open sourced as independent libraries/modules that are not specific to bloXroute's protocol that others can re-use? If so, what components?

The open-source gateway is essentially a message converter between Filecoin and the BDN. We will develop a message converter for the bloXroute BDN. If in the future there are new BDN since it is an open source, it will be an easy change to reuse the same code  

> 2. Will everything be in python or what other languages will you use?

Python and C++ extensions 

> 3. Will users of the BDN require BLXR tokens on Ethereum?

Not at all. BLXR is security not utility token so that it won't be involved or required in any kind of payment or governing process. Filecoin users and validators, who want to take advantage of the BDN, can use bloXroute free tier or purchased a premium tier that enable more data to be sent to the BDN. We can discuss more details on bloXroute business model 

> 4. The proposal doesn't mention hosting the distributed cloud infra for the BDN - how is that funded?

The cloud infra will be hosted by bloXroute. The infra will be shared among all blockchains for the economy of scale unless private infra is required. Its operating cost will be covered by paid users. Before the BDN can earn enough to break even, we are relying on the VC investment to fund our operation.

**Comment by eshon** [comment]
Hi @eyalmarkovich and @steven004,

1. The project description implies this is about researching libp2p integration with bloXroute - useful for other networks using libp2p as well - is that not the case?

2. Why does converting the messages between Filecoin and the BDN require so many developer hours? 

3. Its not clear whether this is needed because Tipsets are designed to collect different messages across the network and block production is epoch and election-based. Also its not clear whether it will complicate the network. Is there any way you could provide evidence its needed or consider breaking this down into a smaller research proposal first as a way to validate this?

**Comment by eyalmarkovich** [comment]
Hi @eshon 

1. Sorry we were not clear on that. The project is not about improving libp2p but on creating a gateway to the BDN which will allow Filecoin to scale. The research proposal is for Filecoin node to continue to use libp2p and the gateway will be connected to the node as a peer. libp2p will still be used by the node and integration to the BDN (via the gateway) will be seamless. Other networks using libp2p will require their own gateway assuming they don't share similar protocol as FileCoin

2. We need to understand the FileCoin protocol (e.g. what messages and their internal structure are being send on the network layer) in order to be able to convert them to the BDN protocol and vise versa. In addition, the gateway is acting as a Filecoin peer so it needs to reply with the proper messages to the node so the node will not drop the connection. You can think of the gateway as a very light implementation of Filecoin node.

3. Let me address the second issue first. As I wrote above, the idea is that the gateway will not replace the p2p network and be augment to it.  A block or transaction that is sent from a node to its peers will arrive via the p2p network or via the gateway. If the gateway wins, the receiving node will be able to process the block/tx message faster. If the p2p network wins nothing is changed from the exiting situation so the gateway can only improve the propagation.
As for the need for the BDN, we believe that it is required to allow Filecoin to scale.
We are aware of Filecoin’s consensus mechanism and its use of Tipsets. bloXroute is compatible with Tipsets, and it can significantly improve its performance and boost Filecoin’s scaling. In particular, to support a high TPS rate, it is necessary to first distribute transactions to the blockchain nodes, which is a challenge on a large distributed network. Once this is accomplished, by utilizing bloXroute’s local short identifiers, the underlying block size can be safely increased, which leads to a high TPS rate. bloXroute does not complicate the network, because our gateway simply communicates with a node as a peer. We are confident that we can scale Filecoin, and we do not find it necessary to start off with a smaller research proposal. We base this on our experience with another GHOSTy protocol, Conflux, which is our partnering project.

**Comment by steven004** [comment]
Adding my 2 cents: 
2. This requests the engineering team understand libp2p protocols, Filecoin blocks and messages design and also the BDN implementation. BloXroute and IPFS-Force covers different parts of these. The both team will work together to figure out the best solution for scalability

3. Filecoin allow blocks select messages, and the tipset mechanism provide a lot of flexibility. However, the design is not really related to the propagation delay reduction. Actually, it increased the chain data by duplicating messages in different blocks, and also increased block numbers than other chains. If the propagation delay is not small enough, we would expect much more forks happening, making it worse.

**Comment by taoshengshi** [comment]
Let us simplify this issue with problem-oriented approach：

1. Filecoin network

- problem : Filecoin network block sync & block propagation issue , for example: [testnet phase1 30 hours to sync](https://filecoinproject.slack.com/archives/CEGN061C5/p1582617641027400)

- solution : filecoin relay(gateway) nodes that are open to API requests from the public, native libp2p and filecoin protocol with enhanced features, no messages converting, no bloxroute protocol involved.

2. Other network interoperability

- problem : network interoperability missing even some projects have shifted to libp2p as layer 0.

- solution : researching libp2p integration with bloXroute - useful for other networks using libp2p as well.   messages converting, and bloxroute protocol integrated.

Is there more cases? Any way we can get started for case 1.

**Comment by eshon** [comment]
Hi @taoshengshi,

This conversation is specifically about the bloXroute proposal for Filecoin.

If you want to discuss lotus syncing it might be better to trust that the lotus team is working on improving syncing, consider [community resources](https://github.com/filecoin-project/docs/wiki) like chain sync snapshots for your own node syncing or search lotus Github for any existing issues and if there isn't discuss there.

But generally, the protocol is still being improved, in the future more optimizations to chain data structures will likely be implemented and there will be ways to figure out better chain syncing strategies like other blockchains have done.

**Comment by taoshengshi** [comment]
Hi @eshon , yeah~ Just add pain points for bloXroute proposal to think ahead.

**Comment by eshon** [comment]
@taoshengshi - Initial syncing and large chain size is a separate issue from block propagation. If you have evidence block propagation is a clear problem right now let us know, but it's specifically about new blocks and reaching consensus, not initial chain sync.

For initial chain sync you can also try using community snapshots (if you trust them): https://github.com/filecoin-project/docs/wiki

**Comment by eshon** [comment]
Greetings,

Thank you for your application to the Filecoin DevGrants program. We appreciate your proposal!

This proposal was not selected in Wave 2.

As the Filecoin implementations advance towards mainnet, the network should initially try to solve performance problems without needing a BDN. Also block propagation delay may not be as much of an issue in an election and epoch-based network like Filecoin's.

If block propagation delay appears to be an issue later on, we would be interested in funding this proposal in a later wave. However right now its not clear whether this will be necessary.

Alternatively, if either of your teams are interested in analyzing the network or running simulations, we could fund research into block timing and network propagation delay as a smaller grant to start. Let us know if that's of interest to your teams.

We appreciate both your teams' thoughtfulness about whether this would be useful for the Filecoin network and hope you continue to be involved in analyzing our network in the future.

**Comment by steven004** [comment]
> Alternatively, if either of your teams are interested in analyzing the network or running simulations, we could fund research into block timing and network propagation delay as a smaller grant to start. Let us know if that's of interest to your teams.

I think it is not only about block timing and network propagation delay, there are some other factors to considered too, including generateCandidates, Winner Calculation, ComputerProofs, and they are related to disk I/O performance. We could consider different model to have some simulations, Or you have any suggestions for this? It is interesting.

**Comment by eshon** [comment]
@steven004 - The libp2p team has built a testground harness (https://github.com/ipfs/testground/) to help teams explore running nodes via simulations. JimPick has started to use it for developing a JS API for lotus but our team has yet to explore running larger simulations. If you have any ideas for this it could be an interesting open grant for Wave 3!

**Pull request closed without merging**
